### ISSUE TITLE
怎样将TFS中的文件导入到阿里云对象存储？

### ISSUE THREAD

**Issue by tianmingxing** [alibaba/tfs#20]
怎样将TFS中的文件导入到阿里云对象存储？我指的是批量导出，目前只能单个单个下载出来。有没有好的方案呢？

**Comment by wangruowr** [comment]
目前没有。TFS的设计就是把文件名交给用户去存的。可以批量来搞。
当然你如果熟悉TFS代码，可以编写一个从每个DS读出块，和文件id来构建文件名（这个工具开源版是不提供的）
