### ISSUE TITLE
淘宝已经放弃tfs了

### ISSUE THREAD

**Issue by yongfa365** [alibaba/tfs#25]
不然为什么没有更新了？

**Comment by wangruowr** [comment]
Thank for watching TFS,
The TFS is still alive but in very stable status, still we will support on bug fix and minor changes,
Free free to let us know your suggestions.

**Comment by nosqldb** [comment]
早没人维护了吧，非常稳定不用维护了:-)？
别的不说，代码能在gcc4.8+编译通过吗？你们从不升级操作系统吗？
